name: Cypress Tests

on:
  push:
    branches:
      - master
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v6
      - run: npm run report:merge
      - run: npm run report:mocha
      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports
