name: Cypress Tests

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v6
      - run: npm run report:merge
      - run: npm run report:mocha
      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-reportx
